<?php
	require_once("../../classes/TemplateUtil.php");
	require_once("../../classes/DBUtil.php");
	require_once("../../classes/SessionUtil.php");
	require_once("../../classes/DeviceAuthUtil.php");
	require_once("../../classes/RelayUtil.php");
	session_start();

	function skip_to($out, $offset) {
		return $out.str_repeat(hex2bin("00"), $offset - (strlen($out)));
	}

	function config_slot($name, $phone_number) {
		$ret = "";
		$nybbles = "0123456789#*";
		$pos = 0;
		$hi = 0;
		if (strlen($phone_number) > 0) {
			// phone number in modified BCD
			foreach (str_split($phone_number) as $num) {
				if ($pos % 2 == 0) {
					$hi = strpos($nybbles, $num) << 4;
					if (!$hi) {
						$hi = 0xE0; // failsafe for invalid char. should this error?
					}
				} else {
					$lo = strpos($nybbles, $num);
					if (!$lo) {
						$lo = 0x0E; // failsafe for invalid char. should this error?
					}
					$ret .= pack('C', $hi | $lo);
				}
				$pos += 1;
			}
			// terminator
			if ($pos % 2 == 0) {
				$ret .= pack('C', 0xF0);
			} else {
				$ret .= pack('C', $hi | 0x0F);
			}
		} else {
			$ret .= hex2bin("FFFFFFFFFFFFFFFF");
		}

		// label
		$ret = skip_to($ret, 8);
		return $ret.$name;
	}

	function checksum($data) {
		$sum = 0;
		foreach (str_split($data) as $byte) {
			$sum += ord($byte);
		}
		return $sum;
	}

	if (SessionUtil::getInstance()->isSessionActive()) {
		$db_util = DBUtil::getInstance();

		$db = $db_util->getDB();

		$stmt = $db->prepare("select email, dion_ppp_id, dion_email_local from sys_users where id = ?");
		$stmt->bind_param("i", $_SESSION["user_id"]);
		$stmt->execute();
		$result = DBUtil::fancy_get_result($stmt)[0];

		// magic
		$out = "MA";
		// dont worry mobile games, its already set up 4 u :3
		$out .= hex2bin("8100");

		// DNS server 1 + 2 -- the real, documented DION DNS servers (per
		// docs/dandocs-magb.md and confirmed byte-for-byte against a genuine
		// pre-2026 mobile_config.bin generated by a real Mobile Trainer cartridge).
		// This field is purely informational (shown on the ISP CONFIG
		// screen) -- actual DNS resolution during a live PPP session always
		// uses the frontend's own --dns1/--dns2, never this EEPROM value --
		// but it should still reflect real, meaningful data rather than
		// whatever IP happened to request this download.
		$out .= pack('C*', 210, 196, 3, 183);
		$out .= pack('C*', 210, 141, 112, 163);

		// gID
		$out .= $result["dion_ppp_id"];//"g".sprintf('%09d',$result["dion_ppp_id"]);

		// email
		$out = skip_to($out, 0x2C);
		$out .= $result["dion_email_local"]."@".ConfigUtil::getInstance()->getConfig()["email_domain_dion"];

		// SMTP server
		$out = skip_to($out, 0x4A);
		$out .= "mail.".ConfigUtil::getInstance()->getConfig()["email_domain_dion"];

		// POP3 server
		$out = skip_to($out, 0x5E);
		$out .= "pop.".ConfigUtil::getInstance()->getConfig()["email_domain_dion"];

		// Config slot 1
		$out = skip_to($out, 0x76);
		$out .= config_slot(ConfigUtil::getInstance()->getConfig()["mobile_center_name"], ConfigUtil::getInstance()->getConfig()["mobile_center_numb"]);

		// Config slot 2
		$out = skip_to($out, 0x8E);
		$out .= config_slot("", "");

		// Config slot 3
		$out = skip_to($out, 0xA6);
		$out .= config_slot("", "");

		// checksum
		$out = skip_to($out, 0xBE);
		$out .= pack('n', checksum($out) % 0x10000);



		// additional data used by libmobile
		$out = skip_to($out, 0x100);
		// magic
		$out .= "LM";
		$out .= hex2bin("00");

		$lib_data = "";

		// adapter model
		$lib_data .= hex2bin("08"); // TODO: pull from user data

		// dns1/dns2 type. libmobile only overrides the game's DNS servers
		// when the type isn't MOBILE_ADDRTYPE_NONE (config.c), so a
		// frontend with its own DNS setting (mGBA/BGB's manual entry in
		// their adapter settings dialog) still wins once the user has
		// saved one -- this just gives every frontend, including one with
		// no such UI (e.g. a libretro core), a working default straight
		// out of the bin, pointed at the same server that answers the
		// games' *.dion.ne.jp queries (see docs, "REON DNS is on port
		// 53").
		$lib_data .= hex2bin("01"); // DNS1 type = MOBILE_ADDRTYPE_IPV4
		// DNS2 fica VAZIO: o REON tem um servidor de DNS só, e repetir o
		// mesmo endereço nos dois campos não dá redundância nenhuma --
		// anuncia um segundo servidor que, quando o primeiro falhar, vai
		// falhar pelo mesmo motivo. Com o tipo em NONE o core nem lê o host
		// e a porta (config_library_load_host só copia quando o tipo é IPV4
		// ou IPV6), e o DNS2 do jogo fica como estava.
		$lib_data .= hex2bin("00"); // DNS2 type = MOBILE_ADDRTYPE_NONE

		// P2P port
		$lib_data .= pack('v', 1027);

		// relay type (offset 0x0a). The relay's *address* is the same for
		// every account (REON only runs the one), so it's written
		// unconditionally here, same as the DNS types above -- only the
		// per-account relay_token below depends on whether this account
		// has been provisioned.
		$lib_data .= hex2bin("01"); // relay type = MOBILE_ADDRTYPE_IPV4

		// relay_token_init (offset 0x0b) + relay_token (offset 0x50-0x5f),
		// relative to this "LM" region -- provisioned at signup
		// (RelayUtil::provisionForUser) instead of negotiated live on first
		// connection. Left unset for accounts that predate this, so those
		// fall back to live negotiation as always.
		$relay = RelayUtil::getInstance()->getForUser($_SESSION["user_id"]);
		if ($relay !== null) {
			$lib_data = skip_to($lib_data, 0x0b - 5);
			$lib_data .= hex2bin("01"); // relay_token_init = true
		}

		// DNS1/DNS2 port (offset 0x1a/0x1c) + relay port (offset 0x1e),
		// relative to this "LM" region. 53 is standard DNS; 31227 is
		// libmobile's own MOBILE_DEFAULT_RELAY_PORT (mobile.h), confirmed
		// against what reon-mobile-relay.service actually listens on.
		$lib_data = skip_to($lib_data, 0x1a - 5);
		$lib_data .= pack('v', 53); // DNS1 port
		$lib_data .= pack('v', 0); // DNS2 port -- sem DNS2, ver acima
		$lib_data .= pack('v', 31227); // relay port

		// DNS1/relay host (offset 0x20/0x40) -- mesmo servidor nos dois, o
		// REON só roda um. O host do DNS2 (0x30) fica zerado pelo skip_to:
		// escrever endereço num campo anunciado como NONE deixaria a bin
		// mostrando um segundo DNS que ninguém usa, para quem a inspecionar.
		$lib_data = skip_to($lib_data, 0x20 - 5);
		$lib_data .= pack('C*', 152, 67, 55, 127); // DNS1 host
		$lib_data = skip_to($lib_data, 0x40 - 5);
		$lib_data .= pack('C*', 152, 67, 55, 127); // relay host

		if ($relay !== null) {
			$lib_data = skip_to($lib_data, 0x50 - 5);
			$lib_data .= $relay["token"];
		}

		// aaaand whatever else is there
		$lib_data = skip_to($lib_data, 0x60 - 5);

		$out .= pack('v', checksum($lib_data) % 0x10000);
		$out .= $lib_data;

		// Device authorization key (outbound relay). Independent section,
		// own magic/checksum, same 5-byte-header pattern as "LM" above --
		// deliberately not mixed into the struct above it so this can be
		// regenerated/relaid-out without touching that checksum. The counter
		// embedded here is always 0: counters are per device on the server
		// (sys_device_counter), a device starts its own from what the bin
		// says and keeps it with its persisted state, and a redownload
		// changes nothing for devices already running (see
		// DeviceAuthUtil::keyForDownload).
		$device_auth_key = DeviceAuthUtil::getInstance()->keyForDownload($_SESSION["user_id"]);
		$da_data = $device_auth_key.pack('P', 0);
		$out = skip_to($out, 0x160);
		$out .= "DA";
		$out .= hex2bin("00");
		$out .= pack('v', checksum($da_data) % 0x10000);
		$out .= $da_data;

		$out = skip_to($out, 0x200);

		// O nome vem daqui, e não só do atributo `download` do link.
		//
		// mobile_config.bin é o nome que o mGBA usa, então é o nome que o
		// arquivo já deve ter ao chegar ao disco -- sem renomear à mão. Sem
		// este cabeçalho, quem abre a URL direto recebe "adapter_config.php",
		// e o nome certo depende de ter vindo pelo botão.
		header("Content-Type: application/octet-stream");
		header('Content-Disposition: attachment; filename="mobile_config.bin"');
		header("Content-Length: " . strlen($out));

		print $out;

	} else {
		// Not signed in: the file is personal, so ask for the login and
		// come back to the account page, where the download button is.
		header("Location: /login.php?next=".rawurlencode("/user/summary.php"));
	}
