#!/usr/bin/env bash
# harden-server.sh — general server security hardening for REON's host.
#
# Deliberately separate from harden-bots.sh (nginx/bot-User-Agent specific)
# and setup-postfix-bridge.sh (mail-specific) — this one is about the host
# itself: brute-force protection, SSH exposure, unused attack surface.
#
# Covers:
#   - fail2ban: bans repeat offenders against sshd and Postfix (both plain
#     connection abuse and SASL auth failures) — this server gets constant
#     scanner/bot traffic on 22/25/110, confirmed in its own logs.
#   - SSH: no root login, no password auth (key-only), no X11 forwarding.
#     Only applied if at least one user already has a key in
#     authorized_keys, specifically to avoid locking out remote access —
#     if that check fails, this step is skipped with a warning instead of
#     risking it.
#   - Disables rpcbind (port 111, RPC/NFS portmapper) — nothing on this
#     server uses NFS, so it's pure unused attack surface.
#   - A few basic nginx response headers (X-Content-Type-Options,
#     X-Frame-Options, Referrer-Policy) — scoped to skip /cgb/, /api/, and /01/,
#     which the Game Boy itself talks to directly and whose minimal ~2001
#     HTTP client doesn't expect (and may choke on) extra response headers.
#
# Idempotent, safe to re-run. Run directly on the server as root:
#   sudo bash harden-server.sh
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "Run as root (sudo bash harden-server.sh)." >&2
    exit 1
fi

c_reset=$'\033[0m'; c_red=$'\033[31m'; c_green=$'\033[32m'; c_yellow=$'\033[33m'; c_blue=$'\033[34m'
log_step()  { printf '\n%s==>%s %s\n' "$c_blue"  "$c_reset" "$*"; }
log_info()  { printf '%s[info]%s %s\n'  "$c_green"  "$c_reset" "$*"; }
log_warn()  { printf '%s[warn]%s %s\n'  "$c_yellow" "$c_reset" "$*" >&2; }
log_error() { printf '%s[error]%s %s\n' "$c_red"    "$c_reset" "$*" >&2; }

apt_install() {
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "$@"
}

install_fail2ban() {
    log_step "Installing and configuring fail2ban"
    apt-get update -qq
    apt_install fail2ban

    cat > /etc/fail2ban/jail.local <<'EOF'
# Generated by harden-server.sh -- do not edit by hand.
[DEFAULT]
bantime = 1h
findtime = 10m
maxretry = 5

[sshd]
enabled = true

[postfix]
enabled = true

[postfix-sasl]
enabled = true
EOF
    systemctl enable --now fail2ban
    systemctl restart fail2ban
    log_info "fail2ban active -- jails: sshd, postfix, postfix-sasl."
}

harden_ssh() {
    log_step "Hardening SSH"
    # Safety first: password authentication is only switched off if at
    # least one authorized key already exists somewhere -- otherwise this
    # could lock remote access out for good (without Oracle's console there
    # is no way back). Skipping beats risking it.
    local has_keys=0
    shopt -s nullglob
    for home in /root /home/*; do
        if [[ -s "$home/.ssh/authorized_keys" ]]; then
            has_keys=1
            break
        fi
    done
    shopt -u nullglob

    if [[ "$has_keys" -ne 1 ]]; then
        log_warn "No authorized_keys found in /root or /home/* -- NOT disabling password login, to avoid locking access out. Sort that out by hand first."
        return
    fi

    local conf="/etc/ssh/sshd_config.d/99-harden-server.conf"
    cat > "$conf" <<'EOF'
# Generated by harden-server.sh
PermitRootLogin no
PasswordAuthentication no
KbdInteractiveAuthentication no
X11Forwarding no
EOF

    if sshd -t; then
        systemctl reload ssh 2>/dev/null || systemctl reload sshd 2>/dev/null || true
        log_info "SSH hardened: no root login, no passwords (key only), no X11 forwarding."
    else
        log_warn "sshd -t failed after the change -- reverting so access is not locked out."
        rm -f "$conf"
    fi
}

disable_unused_services() {
    log_step "Disabling unused services (less attack surface)"
    if systemctl is-enabled rpcbind &>/dev/null || systemctl is-active rpcbind &>/dev/null; then
        systemctl stop rpcbind.service rpcbind.socket 2>/dev/null || true
        systemctl disable rpcbind.service rpcbind.socket 2>/dev/null || true
        systemctl mask rpcbind.service rpcbind.socket 2>/dev/null || true
        log_info "rpcbind (port 111, RPC/NFS) disabled -- this server does not use NFS."
    else
        log_info "rpcbind is already inactive/disabled, nothing to do."
    fi
}

nginx_security_headers() {
    log_step "nginx security headers"
    if ! command -v nginx &>/dev/null; then
        log_warn "nginx not found -- skipping this step."
        return
    fi
    # The pages the Game Boy itself fetches (/cgb/, /api/, /01/) must stay
    # as untouched as possible: the game's HTTP client (Mobile Adapter GB,
    # ~2001) is minimal and strict and expects no extra response headers --
    # a single extra header is a real risk of breaking its parsing. So the
    # security headers below apply only outside /cgb/, /api/ and /01/, via
    # a 'map' keyed on $uri (add_header with an empty value == nginx emits
    # no header).
    cat > /etc/nginx/conf.d/reon-security-headers.conf <<'EOF'
# Generated by harden-server.sh -- do not edit by hand.
# Security headers for the site's human pages only -- NEVER for /cgb/,
# /api/ or /01/, which the Game Boy itself fetches (a minimal ~2001 HTTP
# client that expects no extra response headers).
map $uri $reon_sec_x_content_type_options {
    default "nosniff";
    "~^/(cgb|api|01)/" "";
}
map $uri $reon_sec_x_frame_options {
    default "SAMEORIGIN";
    "~^/(cgb|api|01)/" "";
}
map $uri $reon_sec_referrer_policy {
    default "strict-origin-when-cross-origin";
    "~^/(cgb|api|01)/" "";
}
add_header X-Content-Type-Options $reon_sec_x_content_type_options always;
add_header X-Frame-Options $reon_sec_x_frame_options always;
add_header Referrer-Policy $reon_sec_referrer_policy always;
EOF
    if nginx -t; then
        systemctl reload nginx
        log_info "Security headers active (X-Content-Type-Options, X-Frame-Options, Referrer-Policy) -- except on /cgb/, /api/ and /01/, which the Game Boy fetches directly."
    else
        log_warn "nginx -t failed after the change -- reverting."
        rm -f /etc/nginx/conf.d/reon-security-headers.conf
    fi
}

print_summary() {
    log_step "Summary"
    log_info "fail2ban: $(systemctl is-active fail2ban 2>/dev/null || echo 'not active')"
    log_info "rpcbind: $(systemctl is-active rpcbind 2>/dev/null || echo 'disabled')"
    echo
    log_warn "Not checked/changed automatically by this script:"
    log_warn "  - A firewall rule opening port 9001/tcp with nothing listening on it today."
    log_warn "    Confirm whether it is still needed; if not, remove it with:"
    log_warn "      sudo iptables -D INPUT -p tcp --dport 9001 -j ACCEPT"
}

main() {
    install_fail2ban
    harden_ssh
    disable_unused_services
    nginx_security_headers
    print_summary
}

main "$@"
