#!/usr/bin/env bash
# harden-bots.sh -- blocks search and AI bots/crawlers in reon's nginx, by
# User-Agent, on any host or IP that hits the server.
#
# Deliberately OUTSIDE setup-reon.sh: this script edits the already
# generated config file (${OPT_REON} from outside, sites-enabled from
# inside) instead of coming out of the setup's template. Run it directly
# on the server, as root:
#   sudo bash harden-bots.sh
#
# Effect:
#   - X-Robots-Tag on every response (reinforces the site's robots.txt even
#     for bots that do not read/respect robots.txt).
#   - Immediate 403 for any request whose User-Agent matches the list of
#     known bots (search, AI scraping, scanners) -- whether the request came
#     through the real hostname or straight to the IP, since reon.conf's
#     "server_name _" block answers both.
#   - Neither effect applies to /cgb/, /api/ or /01/: those routes are
#     fetched by the Game Boy itself (Mobile Adapter GB, a minimal ~2001
#     HTTP client) that expects no extra response headers, and whose game
#     User-Agent (e.g. CGB-BXTE-00) must never be judged by the bot
#     heuristic.
#
# IMPORTANT -- does not survive a "sudo bash setup-reon.sh": that script
# regenerates the site from scratch. Run this one again afterwards, every
# time you run setup-reon.sh.
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "Run as root (sudo bash harden-bots.sh)." >&2
    exit 1
fi

SITE_CONF="$(readlink -f /etc/nginx/sites-enabled/reon.conf 2>/dev/null || true)"
if [[ -z "$SITE_CONF" || ! -f "$SITE_CONF" ]]; then
    echo "Could not find /etc/nginx/sites-enabled/reon.conf (did setup-reon.sh run first?)." >&2
    exit 1
fi

BOT_UA_REGEX='bot|crawl|spider|scrape|slurp|archive\.org|ia_archiver|facebookexternalhit|GPTBot|ChatGPT-User|OAI-SearchBot|ClaudeBot|Claude-Web|anthropic-ai|CCBot|Google-Extended|GoogleOther|Bytespider|PetalBot|Amazonbot|Applebot|Meta-External|meta-externalagent|cohere-ai|Diffbot|ImagesiftBot|PerplexityBot|YandexBot|Baiduspider|MJ12bot|AhrefsBot|SemrushBot|DotBot|CensysInspect|Expanse|zgrab|Sogou|Exabot'

# --- X-Robots-Tag on every response, via conf.d (does not touch reon.conf,
# survives any rerun of setup-reon.sh) --------------------------------------
# Except on /cgb/, /api/ and /01/: those pages are fetched by the Game Boy
# itself, whose HTTP client (Mobile Adapter GB, ~2001) is minimal and strict
# and expects no extra headers -- one more is a real risk of breaking its
# parsing. add_header with an empty value makes nginx emit no header.
cat > /etc/nginx/conf.d/reon-robots-header.conf <<EOF
# Generated by harden-bots.sh -- do not edit by hand.
map \$uri \$reon_bots_x_robots_tag {
    default "noindex, nofollow, noarchive, nosnippet, noimageindex, notranslate";
    "~^/(cgb|api|01)/" "";
}
add_header X-Robots-Tag \$reon_bots_x_robots_tag always;
EOF

# --- User-Agent block, injected into every "server {" of reon.conf,
# between markers so this script can run again without duplicating ------
BEGIN_MARK="    # BEGIN harden-bots.sh (does not survive a rerun of setup-reon.sh)"
END_MARK="    # END harden-bots.sh"

tmp="$(mktemp)"
awk -v begin="$BEGIN_MARK" -v end="$END_MARK" -v regex="$BOT_UA_REGEX" '
    BEGIN { skip = 0 }
    $0 == begin { skip = 1; next }
    skip && $0 == end { skip = 0; next }
    skip { next }
    { print }
    /^server[[:space:]]*\{[[:space:]]*$/ {
        print begin
        print "    set $reon_bot_block 0;"
        print "    if ($http_user_agent ~* \"" regex "\") {"
        print "        set $reon_bot_block 1;"
        print "    }"
        print "    # Never block /cgb/, /api/ or /01/ -- the Game Boy itself hits those"
        print "    # routes, and game User-Agents (e.g. CGB-BXTE-00) are short and unusual"
        print "    # enough to collide, in theory, with one of the patterns above."
        print "    if ($request_uri ~ \"^/(cgb|api|01)/\") {"
        print "        set $reon_bot_block 0;"
        print "    }"
        print "    if ($reon_bot_block) {"
        print "        return 403;"
        print "    }"
        print end
    }
' "$SITE_CONF" > "$tmp"

if ! grep -q "^server[[:space:]]*{[[:space:]]*$" "$SITE_CONF"; then
    echo "No 'server {' block found in $SITE_CONF -- aborting without touching anything." >&2
    rm -f "$tmp"
    exit 1
fi

install -m 0644 "$tmp" "$SITE_CONF"
rm -f "$tmp"

if nginx -t; then
    systemctl reload nginx
    echo "OK -- bots blocked by User-Agent in $SITE_CONF, X-Robots-Tag active on every response (except /cgb/, /api/ and /01/, left untouched)."
else
    echo "nginx -t failed after the change -- check $SITE_CONF by hand." >&2
    exit 1
fi
