#!/usr/bin/env bash
# 4-harden-bots.sh -- blocks search and AI bots/crawlers in reon's nginx, by
# User-Agent, on any host or IP that hits the server.
#
# Deliberately OUTSIDE 1-setup-reon.sh: this script edits the already
# generated config file (${OPT_REON} from outside, sites-enabled from
# inside) instead of coming out of the setup's template. Run it directly
# on the server, as root:
#   sudo bash 4-harden-bots.sh
#
# Effect:
#   - X-Robots-Tag on every response (reinforces the site's robots.txt even
#     for bots that do not read/respect robots.txt).
#   - Immediate 403 for any request whose User-Agent matches the list of
#     known bots (search, AI scraping, scanners) -- whether the request came
#     through the real hostname or straight to the IP, since reon.conf's
#     "server_name _" block answers both.
#   - Neither effect applies to /cgb/, /api/, the /NN/ game content or /cgi-bin/mgb/: those
#     routes are fetched by the Game Boy itself (Mobile Adapter GB, a minimal
#     ~2001 HTTP client) that expects no extra response headers, and whose
#     game User-Agent (e.g. CGB-BXTE-00) must never be judged by the bot
#     heuristic. The exemption is matched on $uri, the decoded and normalised
#     path -- see the comment at the injection site: matching the raw
#     $request_uri let a bot claim the exemption with /cgb/%2e%2e/ and be
#     served the page anyway.
#
# IMPORTANT -- the User-Agent rules live INSIDE sites-enabled/reon.conf, and
# "sudo bash 1-setup-reon.sh" regenerates that file from scratch, which takes
# them with it. That script now calls this one at the end for exactly that
# reason (reapply_bot_hardening), so the normal path is covered. This note used
# to say "run this one again afterwards" and be the only protection -- it
# wasn't: the site was regenerated on 08/09/2026 and the blocking was missing,
# unnoticed, until 24/09. If you edit the nginx config by any other means,
# run this again yourself.
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "Run as root (sudo bash 4-harden-bots.sh)." >&2
    exit 1
fi

SITE_CONF="$(readlink -f /etc/nginx/sites-enabled/reon.conf 2>/dev/null || true)"
if [[ -z "$SITE_CONF" || ! -f "$SITE_CONF" ]]; then
    echo "Could not find /etc/nginx/sites-enabled/reon.conf (did 1-setup-reon.sh run first?)." >&2
    exit 1
fi

BOT_UA_REGEX='bot|crawl|spider|scrape|slurp|archive\.org|ia_archiver|facebookexternalhit|GPTBot|ChatGPT-User|OAI-SearchBot|ClaudeBot|Claude-Web|anthropic-ai|CCBot|Google-Extended|GoogleOther|Bytespider|PetalBot|Amazonbot|Applebot|Meta-External|meta-externalagent|cohere-ai|Diffbot|ImagesiftBot|PerplexityBot|YandexBot|Baiduspider|MJ12bot|AhrefsBot|SemrushBot|DotBot|CensysInspect|Expanse|zgrab|Sogou|Exabot'

# Nothing is written before this check: an abort must leave the system as it was.
if ! grep -q "^server[[:space:]]*{[[:space:]]*$" "$SITE_CONF"; then
    echo "No 'server {' block found in $SITE_CONF -- aborting without touching anything." >&2
    exit 1
fi
# Kept so a config that fails `nginx -t` is put back, not left to break the next
# nginx start or the next boot.
SITE_BACKUP="$(mktemp)"
cp -p "$SITE_CONF" "$SITE_BACKUP"
ROBOTS_CONF=/etc/nginx/conf.d/reon-robots-header.conf
ROBOTS_BACKUP="$(mktemp)"
if [[ -f "$ROBOTS_CONF" ]]; then cp -p "$ROBOTS_CONF" "$ROBOTS_BACKUP"; else rm -f "$ROBOTS_BACKUP"; fi

# --- X-Robots-Tag on every response, via conf.d (does not touch reon.conf,
# survives any rerun of setup-reon.sh) --------------------------------------
# Except on /cgb/, /api/, the /NN/ game content and /cgi-bin/mgb/: those pages are fetched by the Game Boy
# itself, whose HTTP client (Mobile Adapter GB, ~2001) is minimal and strict
# and expects no extra headers -- one more is a real risk of breaking its
# parsing. add_header with an empty value makes nginx emit no header.
cat > /etc/nginx/conf.d/reon-robots-header.conf <<EOF
# Generated by 4-harden-bots.sh -- do not edit by hand.
# Keep the exemption pattern identical to the one in 3-harden-server.sh.
map \$uri \$reon_bots_x_robots_tag {
    default "noindex, nofollow, noarchive, nosnippet, noimageindex, notranslate";
    "~^/((cgb|api|[0-9]{2})|cgi-bin/mgb)/" "";
}
add_header X-Robots-Tag \$reon_bots_x_robots_tag always;
EOF

# --- User-Agent block, injected into every "server {" of reon.conf,
# between markers so this script can run again without duplicating ------
# The marker text is matched EXACTLY by the removal below and by the copy already
# in a live reon.conf: do not reword it (that would leave two blocks after a re-run).
BEGIN_MARK="    # BEGIN harden-bots.sh (does not survive a rerun of setup-reon.sh)"
END_MARK="    # END harden-bots.sh"

tmp="$(mktemp)"
awk -v begin="$BEGIN_MARK" -v end="$END_MARK" -v regex="$BOT_UA_REGEX" '
    BEGIN { skip = 0 }
    $0 == begin { skip = 1; next }
    skip && $0 == end { skip = 0; next }
    skip { next }
    { print }
    /^server[[:space:]]*\{[[:space:]]*$/ {
        print begin
        print "    set $reon_bot_block 0;"
        print "    if ($http_user_agent ~* \"" regex "\") {"
        print "        set $reon_bot_block 1;"
        print "    }"
        print "    # Never block /cgb/, /api/, /cgi-bin/mgb/ or the /NN/ game content -- the Game Boy"
        print "    # itself hits those routes, and game User-Agents (e.g. CGB-BXTE-00) are"
        print "    # short and unusual enough to collide, in theory, with one of the"
        print "    # patterns above."
        print "    #"
        print "    # $uri, NOT $request_uri, and that distinction was a real bypass:"
        print "    # $request_uri is the raw line the client sent, while $uri is decoded"
        print "    # and normalised, and it is $uri that decides what gets served. With"
        print "    # $request_uri here, a blocked bot asking for"
        print "    #     /cgb/%2e%2e/pokemon/rankings.php"
        print "    # claimed the exemption on a path starting with /cgb/ and was then"
        print "    # served /pokemon/rankings.php -- measured, byte for byte the same page"
        print "    # a browser gets. Deciding the exemption and the response from the same"
        print "    # variable is what closes that whole class of trick, not any one pattern."
        print "    #"
        print "    # [0-9]{2} rather than a literal 01, to match the redirect rule below:"
        print "    # game content lives under /01/ today, and a second game would be the"
        print "    # kind of change nobody thinks to come back here for."
        print "    if ($uri ~ \"^/((cgb|api|[0-9]{2})|cgi-bin/mgb)/\") {"
        print "        set $reon_bot_block 0;"
        print "    }"
        print "    # robots.txt is served to EVERYONE, blocked agents included, and that"
        print "    # is not an inconsistency. RFC 9309 says a crawler that gets a 4xx on"
        print "    # robots.txt may treat the site as having no restrictions -- so hiding"
        print "    # the file from the very agents it is written for is backwards. Let them"
        print "    # read the ban and leave on their own; the 403 on everything else is"
        print "    # what actually enforces it."
        print "    if ($uri = \"/robots.txt\") {"
        print "        set $reon_bot_block 0;"
        print "    }"
        print "    # And the ACME challenge, for the same reason the redirect below exempts"
        print "    # it: certbot renews by webroot over HTTP, and a renewal that starts"
        print "    # failing does so silently, 90 days from now. [.] instead of an escaped"
        print "    # dot to keep the quoting through awk readable."
        print "    if ($uri ~ \"^/[.]well-known/\") {"
        print "        set $reon_bot_block 0;"
        print "    }"
        print "    if ($reon_bot_block) {"
        print "        return 403;"
        print "    }"
        print end
    }
' "$SITE_CONF" > "$tmp"

install -m 0644 "$tmp" "$SITE_CONF"
rm -f "$tmp"

if nginx -t; then
    systemctl reload nginx
    echo "OK -- bots blocked by User-Agent in $SITE_CONF, X-Robots-Tag active on every response (except /cgb/, /api/, /NN/ and /cgi-bin/mgb/, left untouched)."
    rm -f "$SITE_BACKUP" "$ROBOTS_BACKUP"
else
    echo "nginx -t failed after the change -- putting the previous configuration back." >&2
    install -m 0644 "$SITE_BACKUP" "$SITE_CONF"
    if [[ -f "$ROBOTS_BACKUP" ]]; then install -m 0644 "$ROBOTS_BACKUP" "$ROBOTS_CONF"; else rm -f "$ROBOTS_CONF"; fi
    rm -f "$SITE_BACKUP" "$ROBOTS_BACKUP"
    exit 1
fi
