#!/usr/bin/env python3
"""Generate private Dovecot files; never print credentials.

Dovecot 2.3 gets the same query as the canonical 2.4 template, with only
the documented variable syntax translated. This prevents auth-policy drift.
"""
import argparse
import grp
import json
import os
from pathlib import Path
import re
import secrets

p = argparse.ArgumentParser()
p.add_argument('--version', required=True, choices=['2.3', '2.4'])
p.add_argument('--config', required=True, type=Path)
p.add_argument('--templates', required=True, type=Path)
p.add_argument('--output', type=Path, default=Path('/etc/dovecot'))
a = p.parse_args()
c = json.loads(a.config.read_text())
target = a.output / 'dovecot-sql.conf.ext'
old = target.read_text() if target.exists() else ''
m = re.search(r'^doveadm_password = (.+)$', old, re.M)
password = m.group(1) if m and m.group(1) != 'TROQUE_ME' else secrets.token_hex(24)

def write_private(path, text):
    # Atomic replacement also keeps re-runs from leaving partial auth files.
    tmp = path.with_name(path.name + '.new')
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o640)
    with os.fdopen(fd, 'w') as f:
        f.write(text)
    os.chmod(tmp, 0o640)
    os.chown(tmp, 0, grp.getgrnam('reon').gr_gid)
    os.replace(tmp, path)

if a.version == '2.4':
    text = ('# Generated by the REON installer. Contains credentials.\n'
            'mysql /var/run/mysqld/mysqld.sock {\n'
            f'  user = {c["mysql_user"]}\n  password = {c["mysql_password"]}\n'
            f'  dbname = {c["mysql_database"]}\n}}\n\n'
            f'doveadm_password = {password}\n')
else:
    source = (a.templates / '99-reon.conf').read_text()
    match = re.search(r'^  query = (SELECT .*?)\n}', source, re.M | re.S)
    if not match:
        raise RuntimeError('Canonical authentication query not found')
    query = re.sub(r'\\\s*\n\s*', ' ', match.group(1))
    query = query.replace('%{mechanism}', '%m').replace('%{user|username}', '%n')
    # The 2.3 SQL backend tokenises the connect string independently.
    def sql_value(value):
        value = str(value)
        if any(ch.isspace() for ch in value) or '"' in value or '\\' in value:
            raise ValueError('Dovecot 2.3 connect fields must not contain whitespace, quotes or backslashes')
        return value
    connection = ' '.join(f'{k}={sql_value(v)}' for k, v in {
        'host': '/var/run/mysqld/mysqld.sock', 'dbname': c['mysql_database'],
        'user': c['mysql_user'], 'password': c['mysql_password']}.items())
    write_private(a.output / 'reon-auth-sql.conf.ext',
                  f'driver = mysql\nconnect = {connection}\ndefault_pass_scheme = PLAIN\npassword_query = {query}\n')
    text = f'# Generated; client authentication for doveadm.\ndoveadm_password = {password}\n'
write_private(target, text)
